// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"taa-ex/internal/biz"
	"taa-ex/internal/conf"
	"taa-ex/internal/data"
	"taa-ex/internal/server"
	"taa-ex/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	taaEngineRepo := data.NewTaaEngineRepository(dataData, logger)
	taaEngineHandler := biz.NewTaaEngineHandler(taaEngineRepo, logger)
	taaEngineService := service.NewTaaEngineService(taaEngineHandler, logger)
	grpcServer := server.NewGRPCServer(confServer, taaEngineService, logger)
	httpServer := server.NewHTTPServer(confServer, taaEngineService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
