repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.53.3
    hooks:
      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint run --new-from-rev HEAD --fix
        language: golang
        types: [go]
        exclude: ^vendor/