// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsUserUnspecified(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_USER_UNSPECIFIED.String() && e.Code == 500
}

func ErrorUserUnspecified(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_USER_UNSPECIFIED.String(), fmt.Sprintf(format, args...))
}

func IsUserNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_USER_NOT_FOUND.String() && e.Code == 404
}

func ErrorUserNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_USER_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsUserNotCreated(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_USER_NOT_CREATED.String() && e.Code == 400
}

func ErrorUserNotCreated(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_USER_NOT_CREATED.String(), fmt.Sprintf(format, args...))
}

func IsUserAlreadyExist(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_USER_ALREADY_EXIST.String() && e.Code == 400
}

func ErrorUserAlreadyExist(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_USER_ALREADY_EXIST.String(), fmt.Sprintf(format, args...))
}
