server:
  http:
    addr: 0.0.0.0:8000
    timeout: 5s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:password@tcp(127.0.0.1:3306)/testdb
    #    source: root:@tcp(127.0.0.1:3306)/user_management_db
    max_idle_conns: 10
    max_open_conns: 100
    max_conn_lifetime_in_mins: 60
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s